# Generated by Django 2.2.5 on 2022-01-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
